name: wdaa_dressage_tests_2017
description: A Flutter version of the iOS 2017 WDAA Dressage Tests application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.6

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.5
  audio_video_progress_bar:
  flutter_custom_tabs: ^1.0.2


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  syncfusion_flutter_pdfviewer:
  flutter_launcher_icons:
  flutter_email_sender:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Required for the WDAA Logo image display at the top of the Levels.dart screen
  assets:
    - assets/images/WDAA_Logo_400.jpg
    - assets/images/LargeArenacropped.png
    - assets/images/SmallArenacropped.png
    - assets/images/WDAudio.jpg

    - resources/intro/audios/
    - resources/intro/elements/
    - resources/intro/handbook/
    - resources/intro/scoringshts/
    - resources/intro/testinfo/
    - resources/intro/movements/introT1L/
    - resources/intro/movements/introT1S/
    - resources/intro/movements/introT2L/
    - resources/intro/movements/introT2S/
    - resources/intro/movements/introT3L/
    - resources/intro/movements/introT3S/
    - resources/intro/movements/introT4L/
    - resources/intro/movements/introT4S/

    - resources/basic/audios/
    - resources/basic/elements/
    - resources/basic/handbook/
    - resources/basic/scoringshts/
    - resources/basic/testinfo/
    - resources/basic/movements/basicT1L/
    - resources/basic/movements/basicT1S/
    - resources/basic/movements/basicT2L/
    - resources/basic/movements/basicT2S/
    - resources/basic/movements/basicT3L/
    - resources/basic/movements/basicT3S/
    - resources/basic/movements/basicT4L/
    - resources/basic/movements/basicT4S/

    - resources/L1/audios/
    - resources/L1/elements/
    - resources/L1/handbook/
    - resources/L1/scoringshts/
    - resources/L1/testinfo/
    - resources/L1/movements/L1T1L/
    - resources/L1/movements/L1T2L/
    - resources/L1/movements/L1T3L/
    - resources/L1/movements/L1T4L/

    - resources/L2/audios/
    - resources/L2/elements/
    - resources/L2/handbook/
    - resources/L2/scoringshts/
    - resources/L2/testinfo/
    - resources/L2/movements/L2T1L/
    - resources/L2/movements/L2T2L/
    - resources/L2/movements/L2T3L/
    - resources/L2/movements/L2T4L/

    - resources/L3/audios/
    - resources/L3/elements/
    - resources/L3/handbook/
    - resources/L3/scoringshts/
    - resources/L3/testinfo/
    - resources/L3/movements/L3T1L/
    - resources/L3/movements/L3T2L/
    - resources/L3/movements/L3T3L/
    - resources/L3/movements/L3T4L/

    - resources/L4/elements/
    - resources/L4/handbook/
    - resources/L4/scoringshts/
    - resources/L4/testinfo/
    - resources/L4/movements/L4T1L/
    - resources/L4/movements/L4T2L/
    - resources/L4/movements/L4T3L/
    - resources/L4/movements/L4T4L/



  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
